openapi: 3.0.0

info:
  title: Quantified Self API
  description: |
    #### Capstone Project for Modern Application Development I Course (IIT Madras)
    [GitHub Link](https://github.com/JameelKaisar/Quantified-Self-App)
  contact:
    name: Jameel Kaisar
    email: jameelkaisarkhan@gmail.com
  version: 1.0.0

servers:
  - url: '{protocol}://{host}:{port}/api/{version}'
    variables:
      protocol:
        default: 'http'
        enum:
          - 'http'
      host:
        default: '127.0.0.1'
        enum:
          - '127.0.0.1'
          - 'localhost'
      port:
        default: '8000'
        enum:
          - '8000'
      version:
        default: 'v1'
        enum:
          - 'v1'

components:
  securitySchemes:
    APIToken:
      type: apiKey
      name: APIToken
      in: header

paths:
  /test:
    get:
      summary: Tests if API is working
      description: Tests if API is working
      tags:
        - Test API
      responses:
        '200':
          description: API is working
        '500':
          description: Server error
  
  /checkToken:
    get:
      summary: Test if token is valid
      description: Test if token is valid
      tags:
        - Check Authorization
      responses:
        '200':
          description: Token is valid
        '400':
          description: Missing/invalid parameters
        '401':
          description: Token is invalid
        '500':
          description: Server error
      security:
        - APIToken: []

  /getTrackerTypes:
    get:
      summary: Get types of trackers available
      description: Get types of trackers available
      tags:
        - GET Methods
      responses:
        '200':
          description: Types of trackers available
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    tracker_type_id:
                      type: integer
                      example: 1
                    tracker_type_name:
                      type: string
                      example: Boolean
        '400':
          description: Missing/invalid parameters
        '401':
          description: Token is invalid
        '500':
          description: Server error
      security:
        - APIToken: []

  /getTrackers:
    get:
      summary: Get all trackers
      description: Get all trackers
      tags:
        - GET Methods
      responses:
        '200':
          description: All trackers
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    tracker_id:
                      type: integer
                      example: 1
                    tracker_name:
                      type: string
                      example: Mood
                    tracker_description:
                      type: string
                      example: Some Description of Mood Tracker
                    tracker_type_id:
                      type: integer
                      example: 5
                    tracker_type_name:
                      type: string
                      example: Single Select
                    tracker_unit:
                      type: string
                      example: null
                    tracker_options:
                      type: array
                      items:
                        properties:
                          option_id:
                            type: integer
                            example: 1
                          option_name:
                            type: string
                            example: Happy
        '400':
          description: Missing/invalid parameters
        '401':
          description: Token is invalid
        '500':
          description: Server error
      security:
        - APIToken: []

  /getLogs/{tracker_id}:
    get:
      summary: Get logs of a tracker
      description: Get logs of a tracker
      tags:
        - GET Methods
      parameters:
        - in: path
          name: tracker_id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Logs of a tracker
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    log_id:
                      type: integer
                      example: 1
                    log_time:
                      type: string
                      example: '2022-12-31 23:59'
                    log_note:
                      type: string
                      example: Some Text About Log
                    log_value:
                      type: string
                      example: null
        '400':
          description: Missing/invalid parameters
        '401':
          description: Token is invalid
        '500':
          description: Server error
      security:
        - APIToken: []

  /addTracker:
    post:
      summary: Add a tracker
      description: Add a tracker
      tags:
        - POST Methods
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tracker_name:
                  type: string
                  example: Mood
                tracker_description:
                  type: string
                  example: My Mood Tracker
                tracker_type_id:
                  type: integer
                  example: 5
                tracker_options:
                  type: array
                  example: [Happy, Sad, Angry]
      responses:
        '200':
          description: Tracker Added Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Tracker Added Successfully
                  tracker_id:
                    type: integer
                    example: 1
        '400':
          description: Missing/invalid parameters
        '401':
          description: Token is invalid
        '500':
          description: Server error
      security:
        - APIToken: []

  /addLog/{tracker_id}:
    post:
      summary: Add a tracker log
      description: Add a tracker log
      tags:
        - POST Methods
      parameters:
        - in: path
          name: tracker_id
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                log_time:
                  type: string
                  example: '2022-03-04 02:05'
                log_note:
                  type: string
                  example: Sample Log Note
                log_value:
                  type: array
                  example: [2]
      responses:
        '200':
          description: Log Added Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Log Added Successfully
                  log_id:
                    type: integer
                    example: 1
        '400':
          description: Missing/invalid parameters
        '401':
          description: Token is invalid
        '500':
          description: Server error
      security:
        - APIToken: []

  /deleteTracker/{tracker_id}:
    delete:
      summary: Delete a tracker
      description: Delete a tracker
      tags:
        - DELETE Methods
      parameters:
        - in: path
          name: tracker_id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tracker Deleted Successfully
        '400':
          description: Missing/invalid parameters
        '401':
          description: Token is invalid
        '500':
          description: Server error
      security:
        - APIToken: []

  /deleteLog/{tracker_id}/{log_id}:
    delete:
      summary: Delete a tracker log
      description: Delete a tracker log
      tags:
        - DELETE Methods
      parameters:
        - in: path
          name: tracker_id
          required: true
          schema:
            type: integer
            example: 1
        - in: path
          name: log_id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Log Deleted Successfully
        '400':
          description: Missing/invalid parameters
        '401':
          description: Token is invalid
        '500':
          description: Server error
      security:
        - APIToken: []
